location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connector
    rev: 0.11.0_filip
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
    patches:
      -
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_flight_forge_connector.git
    name: mrs_flight_forge_connector
    rev: 0c71caa7fed3f763e9e2e6e7dc2fb5f8123b4d3e
    type: git
    params:
    sparse_paths:
      - src/
      - include/
    links:
      -
    scripts:
      -
    patches:
      -
default_group: ''
groups:
  -
